name: Dockcross CI

on:
  push:
    branches:
    - 'master'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  image:
    name: ${{ matrix.arch_name }}-${{ matrix.fbsd_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch_name: [aarch64, i686, x86_64]
        fbsd_version: [11.4, 12.2]
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args:
            - ARCH_NAME=${{ matrix.arch_name }}
            - FBSD_VERSION=${{ matrix.fbsd_version }}
          tags: gotson/freebsd-cross-build:${{ matrix.arch_name }}-${{ matrix.fbsd_version }}